server:
  port: 8083
spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

zuul:
  prefix: /api
  routes:
    cloud-client:
      path: /user/**
      serviceId: cloud-client